INSERT INTO SEASON (NAME)
 VALUES ( '2019' );

INSERT INTO PLAYER (NAME)
 VALUES ( 'Renato Barbieri' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Nei Barbieri' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Cristian Costa' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Cristiano Carneiro' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'FC' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jeferson Lucas' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jorge Macedo' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Luzardo Carpes' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Mano' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Mauro' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Otavio Germano' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Ricardo Gothe' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Roberto Bopp' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Robin Antonelo' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Thiago Leao' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Val' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Xico' );  
 