INSERT INTO CHAMPIONSHIP (IDSEASON, NAME, TYPE, ISFINISHED)
 VALUES ( 1, 'Trofeu Abertura 2019', 1, 0 );

 
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Renato Barbieri') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Nei Barbieri') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='FC') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Jeferson Lucas') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Jorge Macedo') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Luzardo Carpes') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Mano') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Mauro') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Roberto Bopp') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Robin Antonelo') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Thiago Leao') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Val') );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT ID FROM PLAYER WHERE NAME='Xico') );

 
INSERT INTO PHASE (IDCHAMPIONSHIP, TYPE, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), 1, 1 );
INSERT INTO PHASE (IDCHAMPIONSHIP, TYPE, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), 2, 2 );
INSERT INTO PHASE (IDCHAMPIONSHIP, TYPE, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), 3, 3 );

 
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '03/19/2019', '20:00', 1 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '03/19/2019', '21:00', 2 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '03/26/2019', '20:00', 3 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '03/26/2019', '21:00', 4 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/01/2019', '20:00', 5 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/01/2019', '21:00', 6 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/09/2019', '20:00', 7 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/09/2019', '21:00', 8 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/16/2019', '20:00', 9 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/16/2019', '21:00', 10 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/22/2019', '20:00', 11 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/22/2019', '21:00', 12 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/30/2019', '20:00', 13 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/30/2019', '21:00', 14 );
 INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '04/30/2019', '22:00', 15 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '05/07/2019', '20:00', 16 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '05/07/2019', '21:00', 17 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '05/07/2019', '22:00', 18 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '05/14/2019', '20:00', 19 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 1), '05/14/2019', '21:00', 20 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 2), '05/21/2019', '20:00', 21 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 2), '05/21/2019', '20:00', 22 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 2), '05/21/2019', '21:00', 23 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 2), '05/21/2019', '21:00', 24 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 2), '05/21/2019', '22:00', 25 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 2), '05/21/2019', '22:00', 26 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 3), '05/28/2019', '20:00', 27 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, IDPHASE, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), (SELECT P.ID FROM PHASE P JOIN CHAMPIONSHIP C ON C.ID = P.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND P.NUMBER = 3), '05/28/2019', '21:00', 28 );
 
INSERT INTO GROUPS (IDCHAMPIONSHIP, NAME)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), 'Grupo A');
INSERT INTO GROUPS (IDCHAMPIONSHIP, NAME)
 VALUES ( (SELECT ID FROM CHAMPIONSHIP WHERE NAME='Trofeu Abertura 2019'), 'Grupo B');

INSERT INTO GROUPMEMBERS (IDGROUP, IDPLAYER)
 VALUES ( (SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo A'), (SELECT ID FROM PLAYER WHERE NAME='Renato Barbieri') );
INSERT INTO GROUPMEMBERS (IDGROUP, IDPLAYER)
 VALUES ( (SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo A'), (SELECT ID FROM PLAYER WHERE NAME='Thiago Leao') );
INSERT INTO GROUPMEMBERS (IDGROUP, IDPLAYER)
 VALUES ( (SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo A'), (SELECT ID FROM PLAYER WHERE NAME='FC') );
INSERT INTO GROUPMEMBERS (IDGROUP, IDPLAYER)
 VALUES ( (SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo A'), (SELECT ID FROM PLAYER WHERE NAME='Jeferson Lucas') );
INSERT INTO GROUPMEMBERS (IDGROUP, IDPLAYER)
 VALUES ( (SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo B'), (SELECT ID FROM PLAYER WHERE NAME='Robin Antonelo') );
INSERT INTO GROUPMEMBERS (IDGROUP, IDPLAYER)
 VALUES ( (SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo B'), (SELECT ID FROM PLAYER WHERE NAME='Mano') );
INSERT INTO GROUPMEMBERS (IDGROUP, IDPLAYER)
 VALUES ( (SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo B'), (SELECT ID FROM PLAYER WHERE NAME='Luzardo Carpes') );
INSERT INTO GROUPMEMBERS (IDGROUP, IDPLAYER)
 VALUES ( (SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo B'), (SELECT ID FROM PLAYER WHERE NAME='Jorge Macedo') );

INSERT INTO GROUPROUNDS (IDGROUP, IDROUND)
 VALUES ((SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo A'), (SELECT R.ID FROM ROUND R JOIN CHAMPIONSHIP C ON C.ID = R.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND R.NUMBER = 21) );
INSERT INTO GROUPROUNDS (IDGROUP, IDROUND)
 VALUES ((SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo A'), (SELECT R.ID FROM ROUND R JOIN CHAMPIONSHIP C ON C.ID = R.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND R.NUMBER = 23) );
INSERT INTO GROUPROUNDS (IDGROUP, IDROUND)
 VALUES ((SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo A'), (SELECT R.ID FROM ROUND R JOIN CHAMPIONSHIP C ON C.ID = R.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND R.NUMBER = 25) );
INSERT INTO GROUPROUNDS (IDGROUP, IDROUND)
 VALUES ((SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo B'), (SELECT R.ID FROM ROUND R JOIN CHAMPIONSHIP C ON C.ID = R.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND R.NUMBER = 22) );
INSERT INTO GROUPROUNDS (IDGROUP, IDROUND)
 VALUES ((SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo B'), (SELECT R.ID FROM ROUND R JOIN CHAMPIONSHIP C ON C.ID = R.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND R.NUMBER = 24) );
INSERT INTO GROUPROUNDS (IDGROUP, IDROUND)
 VALUES ((SELECT G.ID FROM GROUPS G JOIN CHAMPIONSHIP C ON C.ID = G.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND G.NAME = 'Grupo B'), (SELECT R.ID FROM ROUND R JOIN CHAMPIONSHIP C ON C.ID = R.IDCHAMPIONSHIP WHERE C.NAME='Trofeu Abertura 2019' AND R.NUMBER = 26) );
