INSERT INTO SEASON (NAME)
 VALUES ( '2017' );
 
INSERT INTO SEASON (NAME)
 VALUES ( '2018' );

INSERT INTO CHAMPIONSHIP (IDSEASON, NAME, TYPE, ISFINISHED)
 VALUES ( 2, 'Campeonato A', 1, 0 );

INSERT INTO PLAYER (NAME)
 VALUES ( 'Jogador A' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jogador B' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jogador C' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jogador D' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jogador E' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jogador F' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jogador G' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jogador H' );

INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 1 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 2 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 3 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 4 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 5 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 6 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 7 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 8 );

INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '01/07/2018', '19:00', 1 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '01/07/2018', '20:00', 2 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '02/07/2018', '19:00', 3 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '02/07/2018', '20:00', 4 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '03/07/2018', '19:00', 5 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '03/07/2018', '20:00', 6 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '04/07/2018', '19:00', 7 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '04/07/2018', '20:00', 8 );

INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 1, 2, 1, 1, 1, '01/07/2018 22:00', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 3, 4, 2, 2, 0, '01/07/2018 22:00', 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 5, 6, 3, 0, 2, '01/07/2018 22:00', 6 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 7, 8, 4, 0, 1, '01/07/2018 22:00', 8 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 1, 3, 1, 0, 1, '02/07/2018 22:00', 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 2, 4, 2, 3, 0, '02/07/2018 22:00', 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 5, 7, 3, 2, 2, '02/07/2018 22:00', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 6, 8, 4, 1, 0, '02/07/2018 22:00', 6 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 1, 4, 1, 2, 1, '03/07/2018 22:00', 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 2, 3, 2, 3, 3, '03/07/2018 22:00', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 5, 8, 3, 1, 3, '03/07/2018 22:00', 8 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 6, 7, 4, 0, 1, '03/07/2018 22:00', 7 ); 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 4, 1, 5, 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 4, 3, 7, 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 4, 2, 6, 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 4, 4, 8, 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 5, 1, 6, 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 5, 3, 8, 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 5, 2, 5, 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 5, 4, 7, 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 6, 1, 7, 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 6, 3, 5, 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 6, 2, 8, 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 6, 4, 6, 4 );
 INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 7, 1, 8, 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 7, 3, 6, 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 7, 2, 7, 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 7, 4, 5, 4 );
