INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 13, 16, 1, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 15, 8, 2, 2, 1, 'now', 15 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 17, 2, 3, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 4, 14, 4, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 1, 7, 5, 1, 0, 'now', 7 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 9, 10, 6, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 1, 6, 12, 7, 1, 0, 'now', 6 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 13, 17, 1, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 16, 8, 2, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 14, 10, 3, 2, 1, 'now', 14 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 2, 1, 4, 1, 0, 'now', 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 4, 15, 5, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 9, 6, 6, 1, 0, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 2, 7, 12, 7, 0, 0, 'now', 0 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 5, 12, 1, 0, 4, 'now', 12 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 9, 16, 2, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 2, 6, 3, 0, 0, 'now', 14 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 14, 1, 4, 0, 2, 'now', 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 8, 10, 5, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 4, 17, 6, 3, 0, 'now', 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 3, 15, 13, 7, 2, 3, 'now', 13 ); 
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 4, 5, 15, 1, 1, 0, 'now', 5 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 4, 10, 13, 2, 2, 0, 'now', 10 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 4, 11, 2, 3, 1, 3, 'now', 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 4, 4, 12, 4, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 4, 16, 6, 5, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 4, 9, 7, 6, 1, 0, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 4, 15, 13, 7, 2, 3, 'now', 13 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 5, 9, 13, 1, 1, 0, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 5, 7, 17, 2, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 5, 12, 2, 3, 1, 0, 'now', 12 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 5, 11, 8, 4, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 5, 3, 15, 5, 0, 1, 'now', 15 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 5, 3, 11, 6, 3, 1, 'now', 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 5, 3, 17, 7, 3, 2, 'now', 3 );

INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 6, 12, 8, 1, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 6, 9, 14, 2, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 6, 7, 13, 3, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 6, 6, 1, 4, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 6, 9, 17, 5, 4, 0, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 6, 3, 9, 6, 0, 2, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 6, 3, 1, 7, 1, 1, 'now', 0 );

INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 7, 11, 15, 1, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 7, 14, 2, 2, 1, 0, 'now', 14 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 7, 4, 6, 3, 2, 0, 'now', 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 7, 15, 10, 4, 0, 1, 'now', 10 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 7, 5, 1, 5, 1, 0, 'now', 5 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 7, 16, 12, 6, 0, 1, 'now', 12 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 7, 1, 8, 7, 0, 0, 'now', 0 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 8, 11, 10, 1, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 8, 15, 6, 2, 1, 0, 'now', 15 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 8, 4, 1, 3, 2, 0, 'now', 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 8, 3, 6, 4, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 8, 3, 5, 5, 0, 2, 'now', 5 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 8, 3, 13, 6, 4, 3, 'now', 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 8, 3, 4, 7, 0, 0, 'now', 0 );
 

 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 9, 14, 17, 1, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 9, 6, 10, 2, 0, 1, 'now', 10 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 9, 16, 4, 3, 1, 3, 'now', 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 9, 13, 11, 4, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 9, 15, 1, 5, 1, 0, 'now', 15 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 9, 5, 2, 6, 2, 1, 'now', 5 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 10, 15, 2, 1, 2, 0, 'now', 15 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 10, 13, 6, 2, 1, 5, 'now', 6 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 10, 5, 17, 3, 3, 0, 'now', 5 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 10, 11, 16, 4, 1, 2, 'now', 16 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 10, 4, 10, 5, 2, 0, 'now', 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 10, 3, 7, 6, 1, 0, 'now', 3 );

INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 11, 13, 1, 1, 0, 1, 'now', 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 11, 17, 12, 2, 0, 4, 'now', 12 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 11, 15, 9, 3, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 11, 16, 2, 4, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 11, 3, 2, 5, 3, 2, 'now', 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 11, 3, 10, 6, 1, 0, 'now', 3 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 12, 17, 6, 1, 0, 1, 'now', 6 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 12, 11, 9, 2, 0, 2, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 12, 14, 12, 3, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 12, 13, 2, 4, 1, 0, 'now', 13 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 12, 16, 10, 5, 0, 2, 'now', 10 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 12, 9, 5, 6, 1, 0, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 12, 15, 7, 7, 2, 1, 'now', 15 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 12, 14, 8, 8, 2, 0, 'now', 14 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 5, 7, 1, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 7, 4, 2, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 7, 6, 3, 0, 2, 'now', 6 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 1, 9, 4, 1, 2, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 8, 2, 5, 1, 0, 'now', 8 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 10, 12, 6, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 16, 14, 7, 0, 1, 'now', 14 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 11, 17, 8, 1, 0, 'now', 11 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 13, 5, 13, 9, 0, 0, 'now', 0 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 14, 5, 6, 1, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 14, 11, 7, 2, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 14, 13, 8, 3, 0, 1, 'now', 8 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 14, 4, 2, 4, 1, 0, 'now', 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 14, 16, 15, 5, 0, 1, 'now', 15 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 14, 1, 10, 6, 0, 2, 'now', 10 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 15, 17, 7, 1, 2, 0, 'now', 14 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 15, 3, 16, 2, 2, 1, 'now', 3 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 16, 9, 2, 1, 3, 0, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 16, 14, 6, 2, 2, 1, 'now', 14 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 16, 3, 12, 3, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 16, 3, 14, 4, 1, 3, 'now', 14 );
 
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 17, 5, 14, 1, 0, 2, 'now', 14 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 17, 9, 12, 2, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 17, 7, 2, 3, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 17, 6, 8, 4, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 17, 16, 1, 5, 0, 1, 'now', 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 17, 17, 10, 6, 1, 2, 'now', 10 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 17, 11, 4, 7, 0, 3, 'now', 4 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 18, 5, 8, 1, 0, 3, 'now', 8 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 18, 10, 2, 2, 1, 1, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 18, 4, 9, 3, 0, 1, 'now', 9 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 18, 13, 12, 4, 0, 1, 'now', 12 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 18, 17, 1, 5, 0, 0, 'now', 0 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 18, 14, 11, 6, 5, 1, 'now', 14 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 19, 7, 16, 1, 0, 0, 'now', 0 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE, SCORE1, SCORE2, INPUTDATE, IDWINNER)
 VALUES ( 20, 5, 16, 1, 1, 0, 'now', 5 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 21, 12, 11, 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 21, 14, 15, 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 21, 8, 7, 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 21, 5, 10, 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 21, 13, 4, 5 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 21, 16, 17, 6 );

INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 22, 7, 10, 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 22, 15, 12, 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 22, 11, 5, 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 22, 8, 9, 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 22, 13, 14, 5 );

INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 23, 8, 4, 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 23, 11, 6, 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 23, 1, 12, 3 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 23, 15, 17, 4 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 23, 3, 8, 5 );
 
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 24, 5, 4, 1 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 24, 11, 1, 2 );
INSERT INTO GAME ( IDROUND, IDPLAYER1, IDPLAYER2, GAMETABLE)
 VALUES ( 24, 8, 17, 3 );