INSERT INTO SEASON (NAME)
 VALUES ( '2019' );
 
INSERT INTO CHAMPIONSHIP (IDSEASON, NAME, TYPE, ISFINISHED)
 VALUES ( 1, 'Troféu Encerramento 2019', 1, 0 );

INSERT INTO PLAYER (NAME)
 VALUES ( 'Renato Barbieri' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Nei Barbieri' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Cristian Costa' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Cristiano Carneiro' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'FC' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jeferson Lucas' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Jorge Macedo' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Luzardo Carpes' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Mano' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Mauro' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Otávio Germano' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Ricardo Gothe' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Roberto Bopp' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Robin Antonelo' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Thiago Leão' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Val' );
INSERT INTO PLAYER (NAME)
 VALUES ( 'Xico' ); 

INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 1 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 2 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 3 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 4 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 5 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 6 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 7 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 8 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 9 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 10 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 11 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 12 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 13 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 14 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 15 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 16 );
INSERT INTO PARTICIPANT (IDCHAMPIONSHIP, IDPLAYER)
 VALUES ( 1, 17 );

INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '08/06/2019', '20:00', 1 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '08/06/2019', '21:00', 2 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '08/13/2019', '20:00', 3 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '08/13/2019', '21:00', 4 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '08/22/2019', '20:00', 5 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '08/22/2019', '21:00', 6 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '08/29/2019', '20:00', 7 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '08/29/2019', '21:00', 8 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '09/03/2019', '20:00', 9 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '09/03/2019', '21:00', 10 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '09/10/2019', '20:00', 11 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '09/10/2019', '21:00', 12 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '09/17/2019', '20:00', 13 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '09/17/2019', '21:00', 14 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '09/24/2019', '20:00', 15 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '09/24/2019', '21:00', 16 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '10/01/2019', '20:00', 17 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '10/01/2019', '21:00', 18 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '10/05/2019', '13:30', 19 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '10/05/2019', '14:30', 20 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '10/08/2019', '20:00', 21 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '10/08/2019', '21:00', 22 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '10/15/2019', '20:00', 23 );
INSERT INTO ROUND ( IDCHAMPIONSHIP, BASEDATE, BASEHOUR, NUMBER)
 VALUES ( 1, '10/15/2019', '21:00', 24 );